language: python
python:
  - 2.6
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - pip install selenium
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.18.0/geckodriver-v0.18.0-linux64.tar.gz
  - tar -xvzf geckodriver
  - chmod +x geckodriver
  - mv geckodriver /usr/local/bin
install:
  - python bootstrap.py -c .travis.cfg
  - bin/buildout -c .travis.cfg
script:
  - python test1.py
